100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████| 32/32 [00:00<00:00, 504.51it/s]
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████| 32/32 [00:00<00:00, 412.58it/s]
  0%|                                                                                                                       | 0/32 [00:00<?, ?it/s]
Total steps: 10
Warmup steps: 1
Loss = tensor(3.7109, device='cuda:0', grad_fn=<DivBackward0>)
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████| 32/32 [00:00<00:00, 370.46it/s]
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████| 32/32 [00:00<00:00, 499.33it/s]
  0%|                                                                                                                        | 0/2 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "train_tacred_datamap.py", line 197, in <module>
    main()
  File "train_tacred_datamap.py", line 193, in main
    train(args, model, train_features, benchmarks)
  File "train_tacred_datamap.py", line 48, in train
    for index, guid in enumerate(batch[5]):
IndexError: tuple index out of range
Traceback (most recent call last):
  File "train_tacred_datamap.py", line 197, in <module>
    main()
  File "train_tacred_datamap.py", line 193, in main
    train(args, model, train_features, benchmarks)
  File "train_tacred_datamap.py", line 48, in train
    for index, guid in enumerate(batch[5]):
IndexError: tuple index out of range